main/urls.py
from django.urls import path
from main.views import (
    main, contacts
)


app_name = 'main'

urlpatterns = [
    path('', main, name='main'),
    path('contacts/', contacts, name='contacts'),
]

server/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from rest_framework.routers import DefaultRouter
from products.viewsets import ProductViewSet, CategoryViewSet


router = DefaultRouter()
router.register('products', ProductViewSet)
router.register('categories', CategoryViewSet)

urlpatterns = [
    path('api/', include(router.urls)),
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('categories/', include('products.urls.categories')),
    path('accounts/', include('accounts.urls')),
    path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/templates/server/includes/inc_category.html
{% load static %}

<a href="{% url 'categories:detail' pk=id %}"
   class="product_unit">
    {% if image %}
        <img src="{{ image.url }}" alt={{ name }}>
    {% else %}
        <img src="/media/products_images/default.png" alt={{ name }}>
    {% endif %}
    <div class="product_unit_name">
        {{ name }}
    </div>
</a>

server/templates/server/includes/inc_form.html
{% load static %}

<form method="POST" enctype="multipart/form-data">
    {% for err in form.non_field_errors %}
        <div class="alert alert-danger">
            <span>{{ err }}</span>
        </div>
    {% endfor %}

    {% csrf_token %}
    {% for field in form %}
        <div class="create_form">
            <label for="{{ field.name }}">
                {{ field.label }}
            </label>
            {{ field }}

            {% for err in field.errors %}
                <small class="field_error">
                    {{ err }}
                </small>
            {% endfor %}
        </div>
    {% endfor %}
    <input type="submit">
</form>

server/templates/server/includes/inc_main_menu.html
<div class="menu_wrap">
    <div class="menu_wrap_text">Меню</div>
    <ul>
        <li><a href="{% url 'main:main' %}">Главная</a></li>
        <li><a href="{% url 'products:main' %}">Каталог</a>
            <ul>
                <li><a href="{% url 'categories:main' %}">Все категории</a></li>
                {% for category in menu %}
                    <li><a href="{% url 'categories:detail' pk=category.id %}">{{ category.name }}</a>
                        <ul>
                            {# Вместо category.product_set.all используем category.category.all, т.к. #}
                            {# в модели Product в поле category стоит related_name='category' #}
                            {% for product in category.category.all %}
                                <li><a href="{% url 'products:detail' pk=product.id %}">{{ product.name }}</a></li>
                            {% endfor %}
                        </ul>
                    </li>
                {% endfor %}
            </ul>
        </li>
        <li><a href="{% url 'main:contacts' %}">Контакты</a></li>
    </ul>
</div>

server/templates/server/includes/inc_pagination.html
 <ul class="pagination">
    {% if page.has_previous %}
        <li class="pagination_link pagination_link-prev">
            <a
                    href="?page={{ page.previous_page_number }}"
                    class="pagination_link-inner">
                Prev
            </a>
        </li>
    {% endif %}

    {% for num in paginator.page_range %}
        <li class="pagination_link">
            <a
                    href="?page={{ num }}"
                    class="pagination_link-inner">
                {{ num }}
            </a>
        </li>
    {% endfor %}

    {% if page.has_next %}
        <li class="pagination_link pagination_link-next">
            <a
                    href="?page={{ page.next_page_number }}"
                    class="pagination_link-inner">
                Next
            </a>
        </li>
    {% endif %}
</ul>

server/templates/server/includes/inc_product.html
{% load static %}

<a href="{% url 'products:detail' pk=id %}"
   class="product_unit
          {% if status == 'new' %}product_unit_new{% endif %}
          {% if status == 'hot' %}product_unit_hot{% endif %}">
    {% if image %}
        <img src="{{ image.url }}" alt={{ name }}>
    {% else %}
        <img src="/media/products_images/default.png" alt={{ name }}>
    {% endif %}
    <div class="product_unit_name">
        {{ name }}
    </div>
    <div class="product_unit_price_wrap">
        <div class="product_unit_price_actual">{{ price_now }} ₽</div>
        {% if status == 'sale' %}
            <div class="product_unit_price_old"> {{ price_old }} ₽</div>
        {% endif %}
    </div>
</a>